env: "dev"

DB_INFO:
  host: "localhost"
  name: "ApplicationServiceDB"
  user: "postgres"
  pass: "root"
  port: "5432"
  ssl_model: "disable"


HTTP_SERVER_INFO:
  host: "172.16.0.119"
  port: "6611"

JWT_TEMP_INFO:
  key: "lololololololololololololololololololololololololololololol"


#RABBIT_INFO:
#  address_path: "amqp://app:test@172.16.0.94:5672/"
#  queue_name: "files"

ADDITIONAL_ADDRESSES:
  vue: "http://172.16.0.119:5173"