services:
  cshdmediadelivery:
    build:
      context: ./
    container_name: cshdmediadelivery
    environment:
      CONFIG_PATH: "/app/config-yaml/docker.yaml"
    networks:
      - media
    ports:
      - "6611:6611"
    entrypoint: ["/bin/sh", "-c", "./cshdMediaDelivery -config \"$CONFIG_PATH\""]
    depends_on:
      - minio

  minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
    container_name: minio
    networks:
      - media
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

networks:
  media:
    driver: bridge

volumes:
  minio-data: